### ISSUE TITLE
Add tag support

### ISSUE THREAD

**Issue by FiftyFour7250** [gilleswaeber/g-export#1]
Hey, it works absolutely amazing. I like that, unlike other similar projects, all information is saved here. Hidden games are not shown, sort by platform, ratings. But could you please also add tag support? This is really important for sorting and searching.

**Comment by FiftyFour7250** [comment]
And sorting by release year would be great too.

**Comment by gilleswaeber** [comment]
I'll look into it. I would add a command-line parameter to enable exporting the tags since it could be sensitive.

For the release date, I see that the data is in the db, though I'm not sure how accurate it is. Along that we also have publisher, game genre and themes info, so I could try to add that too.
